### ISSUE TITLE
deleting session does not work

### ISSUE THREAD

**Issue by SaeedShurrab** [gridai/gridai#142] opened 2021-11-21 08:59 UTC
## 🐛 Bug

when trying to delete the session, it gives a notification that the session is already deleted but it still running.

### Expected behavior

getting the session deleted 

### Current behavior

session still running 

### To Reproduce

Steps to reproduce the issue

### Environment

 - Browser (e.g., Chrome, Safari):  chrome

**Comment by rusenask** [comment] 2021-11-22 09:12
this does look resolved, the issue is due to datastore being deleted before the session. We have a fix for this in the upcoming release. If you still have this issue @SaeedShurrab  please contact us either here on Slack.

**Closed by rusenask** 2021-11-22 09:12 UTC
Labels: bug
